security:
    providers:
        in_memory:
            memory:
                users:
                        nouchine:   { password: yo, roles: 'ROLE_USER' }
                        ludovic:    { password: yo, roles: 'ROLE_USER' }
                        charles:    { password: yo, roles: 'ROLE_USER' }
                        sofia:      { password: yo, roles: 'ROLE_USER' }
                        cyril:      { password: yo, roles: 'ROLE_USER' }
                        nelly:      { password: yo, roles: 'ROLE_USER' }
                        slim:       { password: yo, roles: 'ROLE_USER' }
                        fabien:     { password: yo, roles: 'ROLE_USER' }
                        rozenn:     { password: yo, roles: 'ROLE_USER' }
                        virginie:   { password: yo, roles: 'ROLE_USER' }
                        suresh:     { password: yo, roles: 'ROLE_USER' }
                        halim:      { password: yo, roles: 'ROLE_USER' }
                        laurent:    { password: yo, roles: 'ROLE_USER' }
                        johann:     { password: yo, roles: 'ROLE_USER' }
                        lydia:      { password: yo, roles: 'ROLE_USER' }
                        dimitri:    { password: yo, roles: 'ROLE_USER' }
                        guillaume:  { password: bla, roles: 'ROLE_ADMIN' }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    access_control:
        - { path: ^/tickets/, roles: ROLE_USER }

    firewalls:
        default:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /
                check_path:  /login_check
            logout:
                path:   /logout
                target: /


    encoders:
        Symfony\Component\Security\Core\User\User: plaintext