<?php

namespace Wf3\TicketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{

    public function getCurrentTickets(){
        $query = $this->createQueryBuilder("t")
                ->select("t")
                ->andWhere("t.isResolved = false")
                ->addOrderBy("t.level", "ASC")
                ->addOrderBy("t.dateCreated", "ASC")
                ->getQuery()
                ;

        $currentTickets = $query->getResult();
        return $currentTickets;
    }

}
